### ISSUE TITLE
Microsoft.Toolkit.HighPerformance dependency not usable with unity3d

### ISSUE THREAD

**Issue by ebolefeysot** [tommyettinger/ShaiRandom#18] opened 2022-12-05 11:49 UTC
Hi
I'm not using directly ShaiRandom, but through GoRogue 3 with unity 3d.
I gave a try to GoRogue3 because GoRogue2 uses a dependency with the monogame framework, and this framework library is rejected by unity3d.
Now, gorogue3 got rid of monogame, and I thought I could use it with unity3d.
But another problematic dependency has been added through ShaiRandom: Microsoft.Toolkit.HighPerformance. This one is also rejected by unity3d.
Is it something really needed by ShiaRandom ? If not, maybe it could a good thing to remove it and be fully compatible with unity3d.
Thanks

**Comment by Chris3606** [comment] 2022-12-06 12:38
Hi!  I'm definitely curious what issue you're running into with HighPerformance and Unity, as off-hand I'm not seeing anything specific to it that should prevent compatibility, if Unity is supporting what they advertise.

For some background, GoRogue [intentionally targets .NET Standard 2.1+](http://www.roguelib.com/articles/2-to-3-upgrade-guide.html#upgraded-to-net-standard-21) in order to use new runtime features, which, as discussed there, excludes .NET Framework as a supported platform.  The article I linked above is a bit out of date; as of 2021.3, Unity does support .NET Standard 2.1 as an API compatibility target (and, worthy of note, regardless of ShaiRandom this is the only way GoRogue would work with it to begin with).

The dependencies for HighPerformance are [less strict than GoRogue](https://github.com/CommunityToolkit/dotnet/blob/main/src/CommunityToolkit.HighPerformance/CommunityToolkit.HighPerformance.csproj#L4); they support .NET Standard 2.0 which GoRogue does not.

So, I wouldn't expect any of the libraries to work properly on versions of Unity prior to 2021.3, including GoRogue itself; but afterwards, I don't see obvious indicators of incompatibility, unless Unity has introduced caveats for library support beyond what they advertise.

Can you provide some details on the Unity version you're using, what the API compatibility target is set to, and the error you receive?

**Comment by Chris3606** [comment] 2022-12-06 13:09
I should also clarify, something I didn't realize; ShaiRandom actually depends on `Microsoft.Toolkit.HighPerformance`, which is _not_ what I linked above; it is has fairly recently been deprecated in favor of `CommunityToolkit.HighPerformance` (which is what I linked; same code, different identity).  ShaiRandom could upgrade here, however, at least as seen on paper, I don't think it would affect the core issue; the dependencies for `Microsoft.Toolkit.HighPerformance` are even less strict than the newer package I referenced above.

Assuming a Unity version >= 2021.3, with the API compatibility target explicitly set to .NET Standard 2.1, the only dependency the high-performance toolkit should have is `System.Runtime.CompilerServices.Unsafe`; it's possible that Unity won't, or my default does not, allow packages with `unsafe` code; not sure on this, though that wouldn't align with traditional dependency management, where unsafe code constraints are not transitive across assemblies, as far as I'm aware.

As far as what code ShaiRandom uses from the high-performance toolkit, as far as I recall/can tell from some basic testing, the only functionality it uses is the `Tokenize` function for `ReadOnlySpan`, in order to [aid in parsing during deserialization](https://github.com/tommyettinger/ShaiRandom/blob/7188a4e068e2b3497c504d833368d44b497d4ead/ShaiRandom/Generators/KnownSeriesRandom.cs#L807) in  `KnownSeriesRandom`.  Assuming that holds true, it is trivially possible to copy that code out of the library and avoid the dependency.  Nonetheless, my primary concern would be why the incompatibility exists in the first place, since on paper it should be equally (actually more) compatible with Unity than GoRogue or ShaiRandom are.  If Unity imposes additional restrictions on packages which are not represented in the dependency graph and the API compatibility targets they support, this may have further implications for ShaiRandom, and GoRogue as well.

**Comment by ebolefeysot** [comment] 2022-12-06 13:35
Hi Chris,
Thank you for the answer. I didn't meet any problem with HighPerformance in unity, it works without any (visible) problems, but when It builds the project, unity specifically excludes this library for compatibility reason (don't remember the exact error message, I will add it later). The message states that the library could make the game crash. It works when running in unity, but doesn't outside (as if the lib was disabled).
I had the same problem with gorogue v2 and monogame library dependency.
Maybe the CommunityToolkit.HighPerformance is accepted. I will give a try by adding it to my project.

**Comment by Chris3606** [comment] 2022-12-06 13:58
Interesting. When you get the chance, if you can post the error message, the version of Unity you're using, and the API compatibility setting from the Unity project settings, it would be much appreciated.

Interestingly, GoRogue never actually "depended" on MonoGame; it did define some implicit conversions in the case where MonoGame was present, but traditional compilers parsed the tags used to include those conversions in such a way that it didn't interpret MonoGame as a hard dependency; Unity interpreted it differently (in my opinion, incorrectly) and tried to assume an unconditional dependency.

Regardless, although it's not on nuget, each version on GoRogue 2 included, in the "releases" tab on the GitHub repository, a "minimal dependency" version which removed the dependency manually and as such would work in Unity.

It's potentially possible to use the same workaround here, if it's necessary; but I'm not convinced the cause is actually the same concept in this case; will have to do some testing and/or analysis of the error message..

**Comment by Chris3606** [comment] 2022-12-07 02:56
@tommyettinger Having difficulty replicating this.  I'm not a Unity expert, so I probably have done something incorrectly or its specific to a target I didn't try.  But I wanted to document what I tried as a starting point.

# Attempt to Reproduce (Failed)

**Unity Version:** 2021.3.15f1

**Steps**
1. Create a new 2d project.
2. Download all GoRogue dependencies manually via nuget:
    - `nuget.exe install GoRogue -Version 3.0.0-beta01 -OutputDirectory .\GoRogue_And_Deps\`
    - `nuget.exe install System.Runtime.CompilerServices.Unsafe -OutputDirectory .\GoRogue_And_Deps\`
3. Install all DLLs downloaded manually into the Unity project via drag and drop.  I used the .net standard 2.1 dll if available, .net standard 2.0 otherwise.  Packages installed included:
    - GoRogue-3.0.0-beta01
    - Microsoft.Toolkit.HighPerformance.7.1.2
    - OptimizedPriorityQueue.4.2.0
    - ShaiRandom.0.0.1
    - System.Runtime.CompilerServices.Unsafe.6.0.0
    - TheSadRogue.Primitives.1.4.1
4. Create a couple prefabs "wall" and "floor" with default materials I can use to spawn for some trivial testing.
5. Create the following script which uses ShaiRandom's generators via GoRogue's `GlobalRandom.DefaultRNG`:
```CS
using GoRogue.Random;
using UnityEngine;
using SadRogue.Primitives;

public class SpawnerGR : MonoBehaviour
{
    public GameObject Wall;
    public GameObject Floor;
    // Start is called before the first frame update
    void Start()
    {
        foreach (var pos in new Rectangle(0, 0, 10, 10).Positions())
        {
            var wall = GlobalRandom.DefaultRNG.NextBool();
            var prefab = wall ? Wall : Floor;

            Instantiate(prefab, new Vector3(pos.X, pos.Y, 0), Quaternion.identity);
        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
```
6. Attach script to a game object in default scene.

No issues building.  Ways I tried to run it:
1. Running via the "play" button in Unity: success
2. Building for Windows target and running the resulting exe: success

Example screenshot of the result I get:
![image](https://user-images.githubusercontent.com/6090062/206075035-1c007967-985d-4398-9bd0-3f296fea1f16.png)

# Questions/Comments
@tommyettinger I can look into removing high-performance toolkit if you want; it shouldn't be that difficult and should simply involve copying the one `Tokenize` function and its dependencies we use from the high-performance toolkit into the base project; it's not a lot of code.  And if that's all you intend to use from the high-performance toolkit, you'd likely cut some binary size out in doing so, so there may be no harm in it.  Nonetheless, I would very much like to better understand the issue here so that appropriate testing can be done and the package requirements for Unity can be better understood.

@ebolefeysot; as I said above, I'm not a Unity expert so there's plenty of things I didn't test, and obviously a whole host of platforms I didn't test.  I'm definitely curious why there seems to be differing behavior though; so feel free to let me know if you have an example project which replicates the issue.  Otherwise, if you have the time, it would be very helpful if you can provide some guidance/clarification on your specific use case:

- What Unity version are you using?
- What target(s) are you building/running for that give you an error?
- What is the set of packages you're installing (name/version)?
- What build/run steps produce the error for you?
- What error do you receive?
- If it's a runtime error, do you have a simple component that can be placed on an object which will cause the error?

**Comment by ebolefeysot** [comment] 2022-12-07 08:52
Hi
I tried to reproduce the problem in the 2021.3.14 version, and I get an error stating that 

ArgumentException: The Assembly System.Runtime.CompilerServices.Unsafe is referenced by Microsoft.Toolkit.HighPerformance. But the dll is not allowed to be included or could not be found.

I spent several days on the same problem with monodevelop library in gorogue v2 where unity reject the library.
I first think that the problem comes from an incompatibility again, but I noticed that the unsafe library was not deployed, although I'm using the gorogue a* algorithm, which cause the shairandom to be deployed.

I don't know actually why I'm missing this lib, but manually adding it remove the error message.
My app is still not working when built outside unity, but that's another point ;)

Anyway, I'm sorry for the false issue and all the time you spent on that subject ..

**Comment by Chris3606** [comment] 2022-12-07 13:15
No problem at all, glad you got it working!

I did notice that the `System.Runtime.CompilerServices.Unsafe` library was not downloaded in my first NuGet command above, which is why I ended up adding the second one.  I'm not sure why this is, it really should have been.  There may be some sort of dependency issue we can work through there.

**Comment by Chris3606** [comment] 2022-12-07 13:16
@tommyettinger , I think we can close this issue, maybe open a different one for the dependency issue/updating the toolkit.

**Comment by tommyettinger** [comment] 2022-12-11 10:17
A lot of the .NET tooling is still very unclear to me, so there could very easily be some unusual issue with NuGet and the versions of different libraries we use... It might take some really deep diving into the NuGet configuration and the dependencies' configurations to get to the bottom of this.

Thanks @Chris3606 for evaluating this issue so thoroughly!

**Closed as completed by tommyettinger** 2022-12-11 10:17 UTC
